/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:32:19 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Pair_ESTest extends Pair_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.setSecond(1860);
      int int0 = pair0.getSnd();
      assertEquals(1860, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.setSecond((-554));
      int int0 = pair0.getSnd();
      assertEquals((-554), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.setFst((String) null);
      pair0.getFst();
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.setFst("&f!L'`ba$O8*");
      pair0.getFst();
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.setSecond(2186);
      pair0.clone();
      assertEquals(2186, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pair pair0 = new Pair("", (-330));
      pair0.clone();
      assertEquals((-330), pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Pair pair0 = null;
      try {
        pair0 = new Pair((Pair) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Pair", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Pair pair0 = new Pair();
      pair0.getFst();
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Pair pair0 = new Pair();
      int int0 = pair0.getSnd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Pair pair0 = new Pair();
      Pair pair1 = new Pair(pair0);
      pair0.setSecond(2186);
      boolean boolean0 = pair0.equals(pair1);
      assertEquals(2186, pair0.getSnd());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Pair pair0 = new Pair();
      Pair pair1 = new Pair("C~VM0?,:4Tbf", (-78));
      boolean boolean0 = pair0.equals(pair1);
      assertFalse(boolean0);
      assertEquals((-78), pair1.getSnd());
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Pair pair0 = new Pair();
      boolean boolean0 = pair0.equals(pair0);
      assertTrue(boolean0);
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Pair pair0 = new Pair();
      Object object0 = new Object();
      boolean boolean0 = pair0.equals(object0);
      assertFalse(boolean0);
      assertEquals(0, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Pair pair0 = new Pair();
      Pair pair1 = pair0.clone();
      assertEquals(0, pair1.getSnd());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Pair pair0 = new Pair();
      String string0 = pair0.toString();
      assertEquals(" ---> 0", string0);
  }
}
