/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:34:25 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startVoluntarios();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startTransportadora();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startSignUp();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startLoja();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startLogIn();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startInicial();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startInformacoesAdicionais();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startEntrega();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startEncomenda();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "exTransportadoraDoesNotExist");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startDefinicoesV();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Hg~V_@M");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startDefinicoesT();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "e kyiXs3");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startDefinicoesC();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "xWV>re=c|KIog");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startCliente();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./TrazAqui.object");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "\nN\u00E3o existe nenhum ficheiro compat\u00EDvel.\nA iniciar...\n");
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.startClassificacoes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      App app0 = null;
      try {
        app0 = new App();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        App.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }
}
