/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:41:02 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class cTopU_ESTest extends cTopU_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      cTopU cTopU0 = new cTopU();
      // Undeclared exception!
      try { 
        cTopU0.compare((Utilizadores) null, (Utilizadores) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cTopU", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      cTopU cTopU0 = new cTopU();
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizadores utilizadores1 = new Utilizadores(utilizadores0);
      Encomenda encomenda0 = new Encomenda();
      utilizadores1.adicionarEncomenda(encomenda0);
      int int0 = cTopU0.compare(utilizadores1, utilizadores0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      cTopU cTopU0 = new cTopU();
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizadores utilizadores1 = new Utilizadores(utilizadores0);
      Encomenda encomenda0 = new Encomenda();
      utilizadores1.adicionarEncomenda(encomenda0);
      int int0 = cTopU0.compare(utilizadores0, utilizadores1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      cTopU cTopU0 = new cTopU();
      Utilizadores utilizadores0 = new Utilizadores();
      int int0 = cTopU0.compare(utilizadores0, utilizadores0);
      assertEquals(0, int0);
  }
}
