/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:32:53 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class exLojaDoesNotExist_ESTest extends exLojaDoesNotExist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      exLojaDoesNotExist exLojaDoesNotExist0 = new exLojaDoesNotExist("");
  }
}
